### ISSUE TITLE
How to get the ground truth models?

### ISSUE THREAD

**Issue by czsc123** [czq142857/IM-NET-pytorch#1]
Hi Zhiqin,

Thanks for the great work.
Can you tell me how to get the ground trouth 256 * 256 * 256 voxel models  and point cloud models?

Best regards,
czsc

**Comment by czq142857** [comment]
You can find related information here:
https://github.com/czq142857/IM-NET

To answer your question:
1. The 256^3 voxel models are from HSP:
https://github.com/chaene/hsp
2. You can find point clouds in many places, such as in AtlasNet repo:
https://github.com/ThibaultGROUEIX/AtlasNet
3. We provide pointcloud files with normal for the shapes in ShapeNet. The points are sampled from only the surface of the shapes. We use floodfilled 256^3 voxel files in HSP to determine whether a point is inside a shape or on its surface.
https://drive.google.com/file/d/16yiTtOrf6m4q9h3ZfhsG07JcAhLvZ0yk/view?usp=drive_open

Best,
Zhiqin
