### ISSUE TITLE
Question on Inference

### ISSUE THREAD

**Issue by Ade-Pyaar** [czq142857/IM-NET-pytorch#12]
Hello @czq142857,
Thanks for sharing the code.

I want to test the model using an external image.
Please can you walk me through the procedure as I cannot see any way to pass an image to the model.

**Comment by czq142857** [comment]
You can refer to any of the testing functions, such as *test_mesh*, and change *batch_view_* to your image. Please also output a few images stored in *self.data_pixels* to get a feel for what images are valid for the input.

**Comment by Ade-Pyaar** [comment]
Do you mean _batch_voxels__ ?

**Comment by czq142857** [comment]
No. It should be *batch_view_* in *modelSVR.py*.
