### ISSUE TITLE
About test

### ISSUE THREAD

**Issue by Kammagod** [czq142857/IM-NET-pytorch#15]
hi,
I want to input only one image without his voxel to reconstruction, is that feasible？

**Comment by czq142857** [comment]
Yes. Please take a look at function *test_image* at *modelSVR.py*.

**Comment by Kammagod** [comment]
> Yes. Please take a look at function _test_image_ at _modelSVR.py_.

Thank you for your help，but in Class IM_SVR，data_hdf5 file is generated using voxels and images. Can I use only images to generate this file? Please give me some suggestions

**Comment by czq142857** [comment]
You can simply remove the data loading code, since the training data is not used in *test_image*.

**Comment by Kammagod** [comment]
> You can simply remove the data loading code, since the training data is not used in _test_image_.

Thank you! but in test, I should use `self.dataset_load = self.dataset_name + '_test'` and `data_hdf5_name = self.data_dir+self.dataset_load+'.hdf5'`，i mean `all_vox256_img_test.hdf5` file can be made just by images without their voxels

**Comment by Kammagod** [comment]
> You can simply remove the data loading code, since the training data is not used in _test_image_.

Thank you! but in test, I should use self.dataset_load = self.dataset_name + '_test' and data_hdf5_name = self.data_dir+self.dataset_load+'.hdf5'，i mean whether all_vox256_img_test.hdf5 file could be made just by images without their voxels?

**Comment by Kammagod** [comment]
Thank you! but in test, I should use `self.dataset_load = self.dataset_name + '_test' `and `data_hdf5_name = self.data_dir+self.dataset_load+'.hdf5'`，i mean whether `all_vox256_img_test.hdf5` file could be made just by images without their voxels?

**Comment by czq142857** [comment]
Yes, you can generate an hdf5 file with only 'pixels'. You can modify the data preparation code to achieve that. But why do you need an hdf5 file if you can directly input images using *test_image*?

**Comment by Kammagod** [comment]
Th

> Yes, you can generate an hdf5 file with only 'pixels'. You can modify the data preparation code to achieve that. But why do you need an hdf5 file if you can directly input images using _test_image_?

There is no 'test_image' in class IM_SVR... In the code downloaded, there is only 'test_mesh' and 'test_mesh_point' method in class IM_SCR, which one is 'test_image'?

**Comment by czq142857** [comment]
Please clone this repo again. I added this function this morning after seeing this issue.

**Comment by Kammagod** [comment]
> Please clone this repo again. I added this function this morning after seeing this issue.

Thank you!
