### ISSUE TITLE
About the original voxel models from HSP

### ISSUE THREAD

**Issue by ghost** [czq142857/IM-NET-pytorch#17]
Hello Zhiqin,

Thanks a lot for sharing the code and your great work!

I‘m reading the 2_gather_256vox_16_32_64.py. If it is convenient, could you please tell me what's the meaning of the data stored in the mat file(HSP)? For example, I don't understand the meaning of the b or b1 vector. 
Maybe with this, I could have a deeper understanding of how to get sampling points(point-value) in voxels.

Thanks,
nzdbgyx

**Comment by czq142857** [comment]
It is just a file type to store voxels. You do not have to know how it is storing voxels, because all you need are the actual voxels stored as NxNxN arrays, which are provided in the code. Also, the mat file type used in HSP is not commonly used; binvox format is more popular.

**Comment by ghost** [comment]
Thank you I really appreciate your help!
