### ISSUE TITLE
Training with the ready-to-use data

### ISSUE THREAD

**Issue by TalBarami** [czq142857/IM-NET-pytorch#19]
Hey and thanks for sharing this repository.
I've been trying to train the AE with the ready-to-use data that you shared.
However, I'm not quite sure about the train-test split or how to acquire the all_vox256 data.
In the link you shared (https://drive.google.com/open?id=1ykE6MB2iW1Dk5t4wRx85MgpggeoyAqu3) I found several zip files, each related to a different type of object.
Inside the data folder there's a _vox.hdf5 file and a _vox_z.hdf5 file, but it is unclear what the model takes as an input. The txt files (table.txt for instance) are empty.
Could you elaborate on these matters?

Thanks a lot,
Tal

**Comment by czq142857** [comment]
You probably downloaded the wrong file or the file was corrupted. Please download the file again from the link.
There should not be any zip files inside the folder IM-NET-pytorch.
Inside the data folder, there should be four files all_vox256_img_test.hdf5, all_vox256_img_test.txt, all_vox256_img_train.hdf5, all_vox256_img_train.txt. The txt files show the training/testing split.

**Comment by TalBarami** [comment]
You are correct. Thanks and sorry. :-)
