### ISSUE TITLE
I can't understand some codes

### ISSUE THREAD

**Issue by zcm2w0116** [czq142857/IM-NET-pytorch#20]
hi, zhiqin

I'm having some trouble reading your code. It bothered me for days.

- I read it for a long time and still can't understand what this function is doing.

![image](https://user-images.githubusercontent.com/49070981/155674999-c4ac24b8-af4d-4b7c-8fce-2af0c2949f63.png)

- or Where should I look for information on this to understand the above code

I'm new to the field.
Sincerely hope to get your answer here, I will be grateful !

Once again, a heartfelt thank you

**Comment by czq142857** [comment]
Hi,

Basically, this function takes the latent code z as input and returns the output shape represented as a grid. The grid size is self.cell_grid_size*self.frame_grid_size (256 by default). You can find these parameters in the code:
```
self.cell_grid_size = 4
self.frame_grid_size = 64
```

For faster inference, the function will first compute a coarse shape on a coarse grid, whose size is defined by self.frame_grid_size. This part is commented by ```#get frame grid values```.

Then, for each voxel in the coarse grid, if it is adjacent to the shape boundary (the voxel is 0 but a neighbor voxel is 1, or the voxel is 1 but a neighbor voxel is 0), it will be recorded in a queue. The queue will only contain coarse voxels close to the shape boundary. This part is commented by ```#get queue and fill up ones```.

Then, we get the fine grid by only computing the voxels close to the shape boundary. The size of the fine grid is self.cell_grid_size*self.frame_grid_size, therefore each coarse voxel in the queue will be split into a grid of fine voxels, with grid size = self.cell_grid_size. Then the implicit field values of those fine voxels will be computed. This part is commented by ```#run queue```. Note that during this process, new coarse voxels will be put into the queue if they are identified as "adjacent to the shape boundary".

After that, the fine voxel grid is returned. Hope this explanation helps.

Best,
Zhiqin

**Comment by zcm2w0116** [comment]
Thank you so much for your helpfulness and such a quick reply. 

I will try my best to understand.

You are the best person in the world！
