### ISSUE TITLE
Have you released the interpolation of 2D Letters?

### ISSUE THREAD

**Issue by dengyuhk** [czq142857/IM-NET-pytorch#21]
Hi, I am curious about the interpolation of the 2D letters, shown in the IM-Net paper. Have you released that part?

**Comment by czq142857** [comment]
The code for 2d and the letter dataset are not released.

It is easy to modify the code for 2d. Please try it yourself.

As for the font dataset, I don't think I can release it, due to copyright issues. But there are publicly available font datasets, so you can use them.

**Comment by dengyuhk** [comment]
Got it. Many thanks for your kind suggestion and explainnation.
