### ISSUE TITLE
About the data preprocess

### ISSUE THREAD

**Issue by zhaoyj96** [czq142857/IM-NET-pytorch#26]
Dear ZhiqinChen:
I want to ask whether the .png files used in [https://github.com/czq142857/IM-NET/blob/master/point_sampling/3_gather_img.py](url) is the .png files generated in [https://github.com/czq142857/IM-NET/blob/master/point_sampling/2_test_hdf5.py](url)?

**Comment by czq142857** [comment]
No. The images are rendered images of ShapeNet shapes provided by [3D-R2N2](https://github.com/chrischoy/3D-R2N2).

Please read the readme: https://github.com/czq142857/IM-NET/tree/master/point_sampling.
