### ISSUE TITLE
Code for latent GAN

### ISSUE THREAD

**Issue by yd-yin** [czq142857/IM-NET-pytorch#6]
Hi Zhiqin,
Thanks for the great work and code.

Sorry but I did not find the code for latent GAN in this repo, like what in the original repo and improved TF repo.

Thanks :)

**Comment by czq142857** [comment]
Hi,

This repo is an implementation of IM-NET with the framework provided by BSP-NET-pytorch (https://github.com/czq142857/BSP-NET-pytorch), therefore it does not include the code for latent GANs.

If you are interested, you can try the code in the original repo, or transfer that part of the code from tf1 to pytorch.

Best,
Zhiqin
