### ISSUE TITLE
inconsistency with AE training config and data

### ISSUE THREAD

**Issue by yd-yin** [czq142857/IM-NET-pytorch#8]
https://github.com/czq142857/IM-NET-pytorch/blob/31b9cb2361321f03d5a99403533c0bee0dd92600/modelAE.py#L152-L163
The numbers here seems inconsistent with the data (sample 16 ** 3 * 2 points for 32^3 voxels, 32 ** 3 points for 64^3 voxels), which may lead to incomplete training.
https://github.com/czq142857/IM-NET-pytorch/blob/31b9cb2361321f03d5a99403533c0bee0dd92600/modelAE.py#L321

  

Also, can I simply assign `self.load_point_batch_size` as `data_points.shape[1]`?

**Comment by czq142857** [comment]
The numbers are consistent with the data, if you downloaded the data from the correct repo.
Please do not use the data or the point sampling code from other repos as they may be incompatible.

Yes, you can simply assign `self.load_point_batch_size` as `data_points.shape[1]`.

**Comment by yd-yin** [comment]
That's true. Thanks a lot.
