### ISSUE TITLE
Visualizing voxel grid

### ISSUE THREAD

**Issue by supriya-gdptl** [czq142857/IM-NET-pytorch#9]
Hello @czq142857,
Thanks for sharing the code.
I would like to visualize the input and output voxel grids that are used to train IM-NET autoencoder. Preferably, renderings of all voxels grids. Could you please tell me what Python package you used to do this?

Thanks

**Comment by czq142857** [comment]
Hi,

To obtain meshes from voxels, I used PyMCubes.

Note that PyMCubes uses Marching Cubes, which extracts the iso-surface implied by the voxels, not the voxels themselves. Therefore, the results are smooth. If you want the results to be made of cubes representing voxels, I do not know a Python package to do that.

For rendering, I used 3ds Max, not a Python package but rather a professional software. You can also use blender, a free version.

You may also try Marching Cubes in scikit-image:
https://scikit-image.org/docs/dev/auto_examples/edges/plot_marching_cubes.html

Best,
Zhiqin

**Comment by supriya-gdptl** [comment]
Sure, will try your suggestion. Thank you for the help!
